-- Seed inicial para mover el contenido educativo desde JSON a Supabase.
-- Ejecuta primero concepts_schema.sql y despues este archivo.

truncate table public.concept_quiz_options, public.concept_quiz_questions, public.concept_quizzes, public.concept_glossary, public.concept_lessons restart identity cascade;

insert into public.concept_lessons (id, slug, level, title, summary, why_it_matters, key_ideas, example, check_question, check_answer, order_index) values
  ('rentabilidad-riesgo', 'rentabilidad-riesgo', 'base', 'Rentabilidad y riesgo', 'La rentabilidad mide cuanto gana o pierde una inversion. El riesgo mide cuanto puede variar ese resultado.', 'Dos decisiones pueden tener la misma rentabilidad esperada, pero no el mismo peligro. Aprender a comparar ambas cosas evita elegir solo por la posible ganancia.', array['Mas rentabilidad potencial suele venir con mas incertidumbre.', 'Una perdida grande necesita una ganancia mayor para recuperarse.', 'El objetivo no es acertar siempre, sino tomar decisiones compensadas.']::text[], 'Si una accion puede subir un 8% pero tambien caer un 20%, la recompensa posible no compensa automaticamente el riesgo.', 'Si una inversion puede ganar mucho pero tambien caer mucho, que deberias mirar ademas de la ganancia potencial?', 'El riesgo asumido, la posible perdida y si la recompensa compensa ese riesgo.', 1),
  ('diversificacion', 'diversificacion', 'base', 'Diversificacion', 'Diversificar consiste en no concentrar todo el capital en una sola empresa, sector o tipo de activo.', 'Reduce el impacto de un error concreto. Si una posicion sale mal, el resto de la cartera puede amortiguar el golpe.', array['No es comprar muchas cosas al azar.', 'Tiene sentido combinar activos que no se comporten igual.', 'Demasiada concentracion aumenta la dependencia de una sola decision.']::text[], 'Una cartera formada solo por tecnologia puede sufrir mucho si el sector cae. Incluir sectores distintos reduce esa dependencia.', 'Diversificar significa comprar cualquier activo solo para tener muchos?', 'No. Significa repartir el riesgo con criterio entre activos o sectores diferentes.', 2),
  ('tendencia', 'tendencia', 'base', 'Tendencia', 'La tendencia describe la direccion dominante del precio: alcista, bajista o lateral.', 'Ayuda a entender el contexto antes de tomar una decision. Comprar contra una tendencia bajista suele exigir mas cautela.', array['Una tendencia alcista tiene maximos y minimos crecientes.', 'Una tendencia bajista tiene maximos y minimos decrecientes.', 'Un mercado lateral no tiene direccion clara.']::text[], 'Si el precio marca varios minimos cada vez mas altos, puede indicar que los compradores estan ganando fuerza.', 'Que suele indicar una secuencia de maximos y minimos crecientes?', 'Una posible tendencia alcista.', 3),
  ('horizonte-temporal', 'horizonte-temporal', 'base', 'Horizonte temporal', 'El horizonte temporal es el tiempo durante el que planeas mantener una idea de inversion o trading.', 'Una misma operacion puede tener sentido a seis meses y no a tres dias. Sin horizonte temporal es facil mezclar expectativas y tomar malas decisiones.', array['El plazo condiciona la forma de analizar una oportunidad.', 'No todos los movimientos cortos invalidan una idea de largo plazo.', 'Tu estrategia debe encajar con el tiempo que puedes esperar.']::text[], 'Una empresa puede caer un 4% en una semana y seguir teniendo sentido para un inversor que piensa a varios anos.', 'Por que importa definir el horizonte temporal antes de invertir?', 'Porque cambia como interpretas el precio, el riesgo y las expectativas de la operacion.', 4),
  ('volatilidad-basica', 'volatilidad-basica', 'base', 'Volatilidad', 'La volatilidad mide cuanto se mueve el precio de un activo en un periodo determinado.', 'No todos los activos se comportan igual. Entender cuanto se mueven ayuda a ajustar expectativas, tamano y tolerancia al riesgo.', array['Mas volatilidad implica mas incertidumbre en el resultado.', 'Un activo muy volatil puede subir rapido, pero tambien caer rapido.', 'La volatilidad no es mala por si sola; depende de como la gestiones.']::text[], 'Dos activos pueden subir un 10% al ano, pero si uno tiene oscilaciones mucho mas bruscas sera mas dificil de mantener psicologicamente.', 'Que te dice la volatilidad de un activo?', 'Te da una idea de cuanto puede moverse y de cuanta incertidumbre tiene su comportamiento.', 5),
  ('liquidez-basica', 'liquidez-basica', 'base', 'Liquidez', 'La liquidez es la facilidad con la que puedes comprar o vender un activo sin alterar demasiado su precio.', 'En activos poco liquidos puedes tener mas dificultad para entrar o salir al precio que esperabas, sobre todo en momentos de tension.', array['Mas liquidez suele significar ejecuciones mas faciles.', 'La falta de liquidez puede aumentar costes y deslizamientos.', 'No basta con tener una buena idea; tambien hay que poder ejecutarla bien.']::text[], 'Una accion poco negociada puede mostrar un precio en pantalla, pero si quieres vender una posicion grande quizas debas aceptar bastante menos.', 'Que riesgo aparece en un activo poco liquido?', 'Que entrar o salir sea mas dificil y que el precio real de ejecucion se aleje del esperado.', 6),
  ('soporte-resistencia', 'soporte-resistencia', 'intermedio', 'Soportes y resistencias', 'Un soporte es una zona donde el precio suele encontrar compradores. Una resistencia es una zona donde suelen aparecer vendedores.', 'Sirven para plantear entradas, salidas y zonas de invalidacion de una idea.', array['Son zonas, no lineas exactas.', 'Un soporte perdido puede convertirse en resistencia.', 'Funcionan mejor si se combinan con volumen, tendencia y riesgo.']::text[], 'Si una accion rebota varias veces cerca de 50 euros, esa zona puede actuar como soporte mientras no se rompa con claridad.', 'Por que es mejor hablar de zonas y no de precios exactos?', 'Porque el mercado rara vez respeta un punto exacto; suele moverse por areas de interes.', 7),
  ('medias-moviles', 'medias-moviles', 'intermedio', 'Medias moviles', 'Una media movil suaviza el precio para ver mejor la direccion general del mercado.', 'Ayuda a filtrar ruido y comparar el precio actual con su comportamiento reciente.', array['Una media corta reacciona antes, pero da mas senales falsas.', 'Una media larga reacciona mas lento, pero filtra mejor el ruido.', 'El cruce de medias no garantiza una operacion rentable.']::text[], 'Si el precio esta por encima de la media de 50 sesiones y esta subiendo, puede reforzar una lectura alcista.', 'Que problema tiene una media movil muy corta?', 'Reacciona rapido, pero puede generar mas senales falsas por el ruido del precio.', 8),
  ('rsi', 'rsi', 'intermedio', 'RSI', 'El RSI es un indicador de momento que intenta medir si un activo esta muy comprado o muy vendido.', 'Puede ayudar a detectar agotamiento, pero no debe usarse como senal aislada.', array['Valores altos pueden indicar sobrecompra.', 'Valores bajos pueden indicar sobreventa.', 'En tendencias fuertes, el RSI puede mantenerse extremo durante tiempo.']::text[], 'Un RSI alto no significa vender automaticamente. Puede indicar fuerza si el activo esta en tendencia alcista.', 'Un RSI alto obliga siempre a vender?', 'No. Hay que interpretarlo junto con tendencia, volumen y contexto.', 9),
  ('volumen', 'volumen', 'intermedio', 'Volumen', 'El volumen refleja cuantas acciones, contratos o unidades se negocian en un periodo.', 'Ayuda a valorar si un movimiento tiene participacion real o si podria ser debil y poco fiable.', array['Un movimiento con volumen suele tener mas conviccion detras.', 'El volumen puede reforzar o debilitar una ruptura.', 'No siempre anticipa el precio, pero aporta contexto.']::text[], 'Si una resistencia se rompe con mucho volumen, la ruptura suele tener mas credibilidad que si apenas hubo actividad.', 'Que puede indicar una ruptura con volumen alto?', 'Que hay mas participacion del mercado y que el movimiento puede tener mas consistencia.', 10),
  ('rupturas-falsas', 'rupturas-falsas', 'intermedio', 'Rupturas falsas', 'Una ruptura falsa ocurre cuando el precio supera una zona clave, pero luego vuelve rapidamente al rango anterior.', 'Ayuda a no comprar o vender impulsivamente solo porque el precio ha tocado un nivel.', array['No toda ruptura es valida por si sola.', 'Conviene mirar volumen, contexto y confirmacion posterior.', 'Las trampas del mercado suelen castigar la impaciencia.']::text[], 'Una accion supera resistencia por la manana, pero cierra el dia por debajo de ella. Eso puede ser una ruptura fallida.', 'Que deberias evitar ante una ruptura?', 'Entrar automaticamente sin confirmar si el movimiento tiene consistencia real.', 11),
  ('relacion-riesgo-beneficio', 'relacion-riesgo-beneficio', 'intermedio', 'Relacion riesgo beneficio', 'La relacion riesgo beneficio compara cuanto puedes perder frente a cuanto aspiras a ganar en una operacion.', 'Ayuda a decidir si una idea compensa antes de entrar, no despues de que el mercado se mueva.', array['Una buena idea no depende solo de acertar la direccion.', 'Perder poco y ganar mas mejora la sostenibilidad del sistema.', 'La relacion debe evaluarse junto con la probabilidad de exito.']::text[], 'Si arriesgas 1 para intentar ganar 3, no necesitas acertar tanto como si arriesgas 1 para ganar 0,5.', 'Cuando se analiza mejor la relacion riesgo beneficio?', 'Antes de abrir la operacion, para decidir si merece la pena.', 12),
  ('drawdown', 'drawdown', 'avanzado', 'Drawdown', 'El drawdown mide la caida desde un maximo hasta un minimo posterior en una cartera o activo.', 'Permite evaluar cuanto dolor puede sufrir una estrategia antes de recuperarse.', array['Una estrategia rentable puede ser mala si sus caidas son demasiado grandes.', 'El drawdown afecta al capital y tambien a la disciplina del inversor.', 'Controlarlo ayuda a sobrevivir a rachas negativas.']::text[], 'Si una cartera pasa de 10.000 a 8.000 euros, ha sufrido un drawdown del 20%.', 'Por que importa el drawdown si una estrategia acaba ganando dinero?', 'Porque una caida excesiva puede hacer que el usuario abandone o no pueda recuperarse bien.', 13),
  ('tamano-posicion', 'tamano-posicion', 'avanzado', 'Tamano de posicion', 'El tamano de posicion define cuanto capital se arriesga en una decision concreta.', 'Es una de las herramientas mas importantes para controlar perdidas y evitar que una sola decision destruya la cartera.', array['No todas las ideas merecen el mismo capital.', 'Arriesgar poco permite aprender y sobrevivir a errores.', 'El tamano debe relacionarse con el stop, la volatilidad y la confianza.']::text[], 'Si decides no perder mas de 100 euros y tu stop esta a 2 euros por accion, el tamano maximo seria 50 acciones.', 'Que relacion hay entre stop y tamano de posicion?', 'Cuanto mas lejos este el stop, menor deberia ser el numero de acciones para mantener controlado el riesgo.', 14),
  ('sesgo-confirmacion', 'sesgo-confirmacion', 'avanzado', 'Sesgo de confirmacion', 'Es la tendencia a buscar informacion que confirma lo que ya pensamos e ignorar senales contrarias.', 'En inversion puede hacer que mantengamos una mala idea demasiado tiempo.', array['Una buena decision tambien busca argumentos en contra.', 'Cambiar de opinion no es fallar; es actualizarse.', 'Las explicaciones de IA ayudan si se usan para cuestionar, no para justificar.']::text[], 'Si quieres comprar una accion, conviene revisar tambien que podria salir mal antes de entrar.', 'Que pregunta ayuda a reducir este sesgo?', 'Que tendria que pasar para demostrar que mi idea era equivocada?', 15),
  ('backtesting', 'backtesting', 'avanzado', 'Backtesting', 'El backtesting consiste en probar una estrategia con datos historicos para ver como se habria comportado.', 'Permite detectar si una idea tiene cierta coherencia antes de arriesgar dinero real, aunque no garantiza resultados futuros.', array['Un backtest no predice el futuro, solo aporta evidencia historica.', 'Cuanto mas realista sea, mas util sera su lectura.', 'Ajustar demasiado una estrategia al pasado puede ser enganoso.']::text[], 'Una estrategia puede parecer brillante en el historico porque estaba demasiado adaptada a ese periodo y luego fallar fuera de muestra.', 'Que error comun puede aparecer al hacer backtesting?', 'Sobreajustar la estrategia al pasado y creer que eso se repetira igual en el futuro.', 16),
  ('correlacion', 'correlacion', 'avanzado', 'Correlacion', 'La correlacion mide hasta que punto dos activos tienden a moverse de forma parecida o diferente.', 'Ayuda a construir carteras mas equilibradas y a no confundir diversificacion con acumular activos que se mueven igual.', array['Dos activos distintos pueden estar muy correlacionados.', 'La diversificacion mejora cuando las piezas no reaccionan igual.', 'La correlacion puede cambiar con el tiempo.']::text[], 'Comprar varias empresas del mismo sector puede parecer diversificar, pero si todas caen juntas la proteccion es limitada.', 'Que problema hay si dos activos de la cartera estan muy correlacionados?', 'Que pueden caer o subir a la vez, reduciendo el efecto real de la diversificacion.', 17),
  ('esperanza-matematica', 'esperanza-matematica', 'avanzado', 'Esperanza matematica', 'La esperanza matematica combina la probabilidad de ganar y perder con el tamano medio de esas ganancias y perdidas.', 'Sirve para evaluar si una estrategia tiene sentido en conjunto, no solo por una operacion aislada.', array['No hace falta acertar siempre para ser rentable.', 'Una estrategia puede ganar poco muchas veces y perder demasiado pocas veces.', 'La clave es la combinacion entre frecuencia de acierto y relacion riesgo beneficio.']::text[], 'Un sistema que acierta el 40% de las veces puede ser rentable si cuando acierta gana mucho mas de lo que pierde cuando falla.', 'Que intenta responder la esperanza matematica de una estrategia?', 'Si, a lo largo de muchas operaciones, la estrategia tiene una expectativa positiva o negativa.', 18),
  ('interes-compuesto', 'interes-compuesto', 'base', 'Interes compuesto', 'El interes compuesto aparece cuando las ganancias se reinvierten y empiezan a generar nuevas ganancias.', 'Ayuda a entender por que el tiempo puede ser tan importante como la rentabilidad anual. Pequenas diferencias repetidas durante anos pueden acabar siendo enormes.', array['No es lo mismo ganar un 10% una vez que mantener buenos resultados durante muchos periodos.', 'Las perdidas tambien afectan al capital sobre el que se calcula el siguiente resultado.', 'Reinvertir y tener paciencia puede ser mas potente que buscar golpes rapidos.']::text[], 'Si tienes 1.000 euros y ganas un 10%, pasas a 1.100. Si el siguiente ano ganas otro 10%, ganas 110 euros, no 100, porque se calcula sobre 1.100.', 'Por que el interes compuesto mejora con el tiempo?', 'Porque las ganancias acumuladas aumentan la base sobre la que se calculan las ganancias futuras.', 19),
  ('acciones-etfs-indices', 'acciones-etfs-indices', 'base', 'Acciones, ETFs e indices', 'Una accion representa una parte de una empresa. Un ETF agrupa varios activos. Un indice resume el comportamiento de un conjunto de valores.', 'Distinguirlos evita comparar productos que no tienen el mismo riesgo ni la misma funcion dentro de una cartera.', array['Una accion concentra el resultado en una empresa concreta.', 'Un ETF puede repartir la exposicion entre muchas empresas o activos.', 'Un indice no siempre se compra directamente; normalmente se replica mediante fondos o ETFs.']::text[], 'Comprar una accion de Apple no es lo mismo que comprar un ETF del S&P 500, que incluye muchas companias.', 'Que diferencia basica hay entre una accion y un ETF diversificado?', 'La accion depende de una empresa concreta; el ETF reparte la exposicion entre varios activos.', 20),
  ('dividendos', 'dividendos', 'base', 'Dividendos', 'Un dividendo es una parte del beneficio que una empresa puede repartir entre sus accionistas.', 'Ayuda a entender que la rentabilidad de una inversion no siempre viene solo de que suba el precio.', array['No todas las empresas pagan dividendos.', 'Un dividendo alto no garantiza una buena inversion.', 'Conviene mirar si el pago es sostenible con los beneficios de la empresa.']::text[], 'Una empresa puede subir poco en bolsa pero repartir dividendos periodicos, generando parte de la rentabilidad por esa via.', 'Un dividendo alto siempre significa que una inversion es buena?', 'No. Hay que comprobar si la empresa puede sostenerlo y si el riesgo compensa.', 21),
  ('precio-valor', 'precio-valor', 'base', 'Precio y valor', 'El precio es lo que el mercado paga hoy. El valor intenta estimar lo que un activo podria valer segun sus fundamentos y expectativas.', 'Evita pensar que algo es bueno solo porque sube o malo solo porque cae. Precio y valor pueden separarse durante bastante tiempo.', array['El precio cambia cada dia por oferta y demanda.', 'El valor depende de beneficios, crecimiento, riesgo y expectativas.', 'Comprar barato no significa comprar bien si el valor real tambien esta cayendo.']::text[], 'Una accion puede parecer barata porque ha caido un 50%, pero si el negocio se ha deteriorado mucho quizas no este infravalorada.', 'Por que no basta con mirar si una accion ha caido mucho?', 'Porque hay que valorar si el negocio sigue teniendo valor o si la caida refleja un deterioro real.', 22),
  ('varianza-desviacion', 'varianza-desviacion', 'intermedio', 'Varianza y desviacion estandar', 'La varianza mide la dispersion de los rendimientos respecto a su media. La desviacion estandar es su raiz cuadrada y suele usarse como medida de volatilidad.', 'Permite pasar de una sensacion general de riesgo a una medida calculable. Asi puedes comparar activos con mas criterio.', array['Primero calculas la media de los rendimientos.', 'Despues mides cuanto se aleja cada rendimiento de esa media.', 'Elevar al cuadrado evita que diferencias positivas y negativas se cancelen.']::text[], 'Con rendimientos 2%, 4% y 6%, la media es 4%. Las diferencias son -2, 0 y 2 puntos; al cuadrarlas obtienes 4, 0 y 4, cuya media da la varianza.', 'Por que se elevan al cuadrado las diferencias al calcular varianza?', 'Para que las desviaciones negativas y positivas no se cancelen y para penalizar mas los movimientos grandes.', 23),
  ('rentabilidad-real-nominal', 'rentabilidad-real-nominal', 'intermedio', 'Rentabilidad real y nominal', 'La rentabilidad nominal es la ganancia antes de ajustar por inflacion. La rentabilidad real descuenta la perdida de poder adquisitivo.', 'Ganar dinero en terminos nominales no siempre significa mejorar tu capacidad de compra.', array['La inflacion reduce el valor del dinero con el tiempo.', 'La rentabilidad real aproxima cuanto aumenta tu poder adquisitivo.', 'Una rentabilidad nominal baja puede ser negativa en terminos reales si la inflacion es alta.']::text[], 'Si ganas un 4% pero la inflacion es del 6%, tu rentabilidad real aproximada es negativa.', 'Que tiene en cuenta la rentabilidad real que no incluye la nominal?', 'El efecto de la inflacion sobre el poder adquisitivo.', 24),
  ('per-valoracion', 'per-valoracion', 'intermedio', 'PER y valoracion', 'El PER compara el precio de una accion con el beneficio por accion de la empresa.', 'Sirve como primera referencia de valoracion, aunque nunca deberia usarse sin contexto.', array['Un PER alto puede reflejar expectativas de crecimiento.', 'Un PER bajo puede indicar oportunidad o problemas del negocio.', 'Compararlo con empresas similares suele ser mas util que mirarlo aislado.']::text[], 'Una empresa con PER 30 puede no estar cara si crece mucho y de forma sostenible; otra con PER 8 puede estar barata o estar deteriorandose.', 'Por que un PER bajo no garantiza que una accion este barata?', 'Porque puede reflejar expectativas negativas o deterioro de beneficios futuros.', 25),
  ('costes-comisiones-slippage', 'costes-comisiones-slippage', 'intermedio', 'Costes, comisiones y slippage', 'Las comisiones son costes explicitos. El slippage es la diferencia entre el precio esperado y el precio real de ejecucion.', 'Una estrategia que parece rentable en teoria puede dejar de serlo al incluir costes reales, sobre todo si opera con mucha frecuencia.', array['Los costes pequenos se acumulan si operas mucho.', 'El slippage suele empeorar en activos poco liquidos o momentos de tension.', 'Un buen analisis debe incluir el precio real al que puedes ejecutar.']::text[], 'Si una operacion espera ganar un 0,3% pero entre comisiones y slippage pierde 0,2%, el margen real es mucho menor.', 'Que es el slippage?', 'La diferencia entre el precio que esperabas ejecutar y el precio final al que se ejecuta la operacion.', 26),
  ('beta-mercado', 'beta-mercado', 'avanzado', 'Beta frente al mercado', 'La beta mide la sensibilidad de un activo frente a los movimientos del mercado de referencia.', 'Ayuda a entender si una cartera esta tomando mas o menos riesgo sistematico que el mercado.', array['Una beta mayor que 1 suele moverse mas que el mercado.', 'Una beta menor que 1 suele moverse menos que el mercado.', 'La beta es historica y puede cambiar si cambia el negocio o el entorno.']::text[], 'Si una accion tiene beta 1,5, podria moverse aproximadamente un 1,5% cuando el mercado se mueve un 1%, aunque no es una regla exacta.', 'Que sugiere una beta superior a 1?', 'Que el activo tiende a moverse con mas intensidad que el mercado de referencia.', 27),
  ('sharpe', 'sharpe', 'avanzado', 'Ratio Sharpe', 'El ratio Sharpe compara el exceso de rentabilidad de una estrategia con la volatilidad asumida.', 'Permite distinguir entre ganar mucho por habilidad o ganar mucho asumiendo movimientos muy bruscos.', array['Relaciona rentabilidad con riesgo medido como volatilidad.', 'Un Sharpe mayor suele indicar mejor rentabilidad ajustada al riesgo.', 'Debe compararse entre estrategias similares y periodos coherentes.']::text[], 'Dos estrategias ganan un 12%, pero si una lo hace con la mitad de volatilidad, su rentabilidad ajustada al riesgo puede ser mejor.', 'Que intenta medir el ratio Sharpe?', 'Cuanta rentabilidad extra se obtiene por unidad de volatilidad asumida.', 28),
  ('apalancamiento', 'apalancamiento', 'avanzado', 'Apalancamiento', 'El apalancamiento permite tomar una exposicion mayor que el capital propio usando deuda, margen o derivados.', 'Puede amplificar beneficios, pero tambien perdidas. Mal gestionado, convierte un error pequeno en un problema grande.', array['Aumenta la sensibilidad de la cartera a movimientos del mercado.', 'Puede generar llamadas de margen si las perdidas superan ciertos limites.', 'No sustituye a una buena gestion del riesgo.']::text[], 'Con apalancamiento 2:1, un movimiento del 5% en el activo puede implicar aproximadamente un 10% sobre tu capital, antes de costes.', 'Cual es el principal peligro del apalancamiento?', 'Que amplifica las perdidas igual que puede amplificar las ganancias.', 29),
  ('regimen-mercado', 'regimen-mercado', 'avanzado', 'Regimen de mercado', 'Un regimen de mercado describe el entorno dominante: tendencia fuerte, lateralidad, alta volatilidad, baja volatilidad o crisis.', 'Una estrategia puede funcionar muy bien en un entorno y mal en otro. Reconocer el regimen evita aplicar siempre la misma receta.', array['Los mercados no se comportan igual en todos los periodos.', 'Volatilidad, correlaciones y liquidez pueden cambiar rapidamente.', 'Una estrategia robusta debe saber cuando reducir exposicion.']::text[], 'Una estrategia de comprar rupturas puede funcionar en tendencias fuertes y sufrir muchas senales falsas en mercados laterales.', 'Por que importa detectar el regimen de mercado?', 'Porque la eficacia de una estrategia depende mucho del entorno en el que se aplica.', 30);

insert into public.concept_glossary (id, term, definition, order_index) values
  ('activo', 'Activo', 'Instrumento financiero como una accion, criptomoneda, indice o ETF.', 1),
  ('volatilidad', 'Volatilidad', 'Medida de cuanto se mueve el precio. Mas volatilidad implica mas incertidumbre.', 2),
  ('liquidez', 'Liquidez', 'Facilidad para comprar o vender sin mover demasiado el precio.', 3),
  ('stop', 'Stop', 'Nivel definido para limitar una perdida si la idea no funciona.', 4),
  ('horizonte-temporal', 'Horizonte temporal', 'Tiempo durante el que se espera mantener una decision.', 5),
  ('backtest', 'Backtest', 'Prueba de una estrategia con datos historicos.', 6),
  ('varianza', 'Varianza', 'Medida de dispersion que calcula cuanto se alejan los resultados de su media, elevando esas diferencias al cuadrado.', 7),
  ('desviacion-estandar', 'Desviacion estandar', 'Raiz cuadrada de la varianza. En finanzas se usa mucho para expresar volatilidad en las mismas unidades que los rendimientos.', 8),
  ('dividendo', 'Dividendo', 'Parte del beneficio que una empresa puede repartir entre sus accionistas.', 9),
  ('capitalizacion', 'Capitalizacion bursatil', 'Valor de mercado aproximado de una empresa: precio de la accion multiplicado por el numero de acciones.', 10),
  ('per', 'PER', 'Relacion precio-beneficio. Compara el precio de una accion con el beneficio que genera la empresa por accion.', 11),
  ('rentabilidad-compuesta', 'Rentabilidad compuesta', 'Crecimiento que se calcula reinvirtiendo ganancias, de forma que los beneficios tambien generan nuevos beneficios.', 12),
  ('apalancamiento', 'Apalancamiento', 'Uso de deuda o derivados para aumentar exposicion. Puede amplificar ganancias, pero tambien perdidas.', 13),
  ('beta', 'Beta', 'Medida de sensibilidad de un activo frente al mercado. Una beta alta suele implicar movimientos mas intensos que el indice.', 14);

insert into public.concept_quizzes (level, title, description, xp_reward_per_correct, xp_penalty_per_wrong) values
  ('base', 'Test de fundamentos', 'Comprueba si dominas riesgo, diversificacion, tendencia y los pilares basicos antes de pasar al siguiente bloque.', 15, 5),
  ('intermedio', 'Test de lectura tecnica', 'Valida si sabes interpretar zonas, indicadores y estructuras sin depender de una sola senal.', 20, 8),
  ('avanzado', 'Test de gestion avanzada', 'Cierra el recorrido con gestion del riesgo, psicologia, backtesting y construccion de carteras.', 25, 10);

insert into public.concept_quiz_questions (id, quiz_level, question, correct_option_id, explanation, order_index) values
  ('base-1', 'base', 'Si una inversion promete mucha rentabilidad, que deberias revisar tambien?', 'b', 'La rentabilidad sin contexto no sirve. Siempre hay que compararla con el riesgo asumido y con la posible perdida.', 1),
  ('base-2', 'base', 'Que significa diversificar correctamente?', 'c', 'Diversificar no es acumular activos al azar, sino repartir el riesgo entre activos o sectores que no dependan todos de lo mismo.', 2),
  ('base-3', 'base', 'Una secuencia de maximos y minimos crecientes suele indicar:', 'a', 'Cuando tanto los maximos como los minimos suben de forma progresiva, suele haber una estructura alcista.', 3),
  ('base-4', 'base', 'Que problema tiene concentrar toda la cartera en una sola empresa?', 'b', 'La concentracion aumenta mucho la dependencia de una sola idea. Si sale mal, el impacto en la cartera es mucho mayor.', 4),
  ('base-5', 'base', 'En un mercado lateral, que suele pasar con la direccion del precio?', 'c', 'En un lateral no hay una direccion dominante clara; el precio se mueve dentro de un rango sin tendencia definida.', 5),
  ('base-6', 'base', 'Si una posicion cae mucho, por que cuesta mas recuperarse?', 'a', 'Tras una gran perdida, hace falta una rentabilidad porcentual mayor para volver al punto inicial. Por eso controlar caidas es tan importante.', 6),
  ('base-7', 'base', 'Que define el horizonte temporal de una inversion?', 'b', 'El horizonte temporal es el tiempo previsto para mantener una idea, y condiciona el analisis, el riesgo y la paciencia necesaria.', 7),
  ('base-8', 'base', 'Que indica principalmente la volatilidad?', 'a', 'La volatilidad da una idea de cuanto puede moverse un activo y, por tanto, de cuanta incertidumbre tiene su comportamiento.', 8),
  ('base-9', 'base', 'Que ventaja aporta un activo liquido?', 'c', 'La liquidez facilita entrar o salir del mercado sin distorsionar demasiado el precio, algo clave cuando necesitas ejecutar una decision.', 9),
  ('base-10', 'base', 'Que error suele cometer alguien que solo mira la posible ganancia?', 'b', 'Centrarse solo en lo que se puede ganar hace olvidar cuanto se puede perder y si el escenario realmente compensa el riesgo.', 10),
  ('base-11', 'base', 'Que suele ser mas prudente si no entiendes bien un activo?', 'a', 'Si no comprendes el activo o su riesgo, lo sensato es reducir exposicion o simplemente no entrar todavia.', 11),
  ('base-12', 'base', 'Que relacion existe entre diversificacion y concentracion?', 'c', 'La diversificacion reduce dependencia de una sola idea; la concentracion hace justo lo contrario.', 12),
  ('base-13', 'base', 'Que explica el interes compuesto?', 'a', 'El interes compuesto aparece cuando las ganancias se reinvierten y pasan a formar parte del capital que genera ganancias futuras.', 13),
  ('base-14', 'base', 'Si ganas un 10% sobre 1.000 euros y reinviertes, sobre que capital se calcula el siguiente 10%?', 'b', 'Despues del primer 10%, el capital pasa a 1.100 euros. Si reinviertes, el siguiente rendimiento se calcula sobre esa nueva base.', 14),
  ('base-15', 'base', 'Que diferencia basica hay entre una accion y un ETF diversificado?', 'c', 'Una accion concentra el resultado en una empresa concreta. Un ETF diversificado reparte la exposicion entre varios activos.', 15),
  ('base-16', 'base', 'Que representa un indice bursatil?', 'a', 'Un indice resume el comportamiento de un conjunto de valores, como una fotografia agregada de una parte del mercado.', 16),
  ('base-17', 'base', 'Un dividendo alto significa siempre que una accion es buena?', 'b', 'Un dividendo alto puede ser atractivo, pero tambien puede ser insostenible si el negocio no genera beneficios suficientes.', 17),
  ('base-18', 'base', 'Que diferencia hay entre precio y valor?', 'c', 'El precio es lo que el mercado paga hoy. El valor intenta estimar lo que deberia valer un activo segun sus fundamentos y expectativas.', 18),
  ('base-19', 'base', 'Por que una accion que ha caido mucho no es automaticamente barata?', 'a', 'Una gran caida puede reflejar que el negocio se ha deteriorado. Para saber si esta barata hay que comparar precio con valor esperado.', 19),
  ('base-20', 'base', 'Que suele aportar el tiempo a una estrategia de largo plazo bien planteada?', 'b', 'El tiempo permite que la reinversion y la acumulacion de rendimientos trabajen a favor, aunque no elimina el riesgo.', 20),
  ('intermedio-1', 'intermedio', 'Por que hablamos de soporte y resistencia como zonas?', 'b', 'El mercado rara vez gira en un precio exacto. Normalmente reacciona en areas donde se concentra el interes comprador o vendedor.', 1),
  ('intermedio-2', 'intermedio', 'Que desventaja tiene una media movil muy corta?', 'a', 'Una media muy corta reacciona muy rapido, pero tambien absorbe mucho ruido y puede lanzar mas senales falsas.', 2),
  ('intermedio-3', 'intermedio', 'Que significa un RSI alto por si solo?', 'c', 'El RSI no debe leerse de forma aislada. Un valor alto puede ser agotamiento o simplemente fuerza en una tendencia alcista.', 3),
  ('intermedio-4', 'intermedio', 'Si un soporte se rompe con claridad, que puede pasar despues?', 'b', 'Una zona que antes frenaba caidas puede pasar a actuar como resistencia si el precio intenta recuperarla desde abajo.', 4),
  ('intermedio-5', 'intermedio', 'Que ventaja suele tener una media movil larga frente a una corta?', 'c', 'Las medias largas reaccionan mas despacio, pero filtran mejor el ruido y muestran mejor la direccion general.', 5),
  ('intermedio-6', 'intermedio', 'Que combinacion mejora la lectura de soportes o resistencias?', 'a', 'Estas zonas funcionan mejor cuando se apoyan en mas contexto: volumen, tendencia, volatilidad y gestion del riesgo.', 6),
  ('intermedio-7', 'intermedio', 'Que puede indicar una ruptura con volumen alto?', 'b', 'Cuando una ruptura viene acompanada de volumen elevado, suele haber mas participacion del mercado y mas conviccion detras del movimiento.', 7),
  ('intermedio-8', 'intermedio', 'Que es una ruptura falsa?', 'c', 'Una ruptura falsa supera temporalmente una zona clave, pero luego el precio vuelve al rango previo y atrapa a quien entro demasiado pronto.', 8),
  ('intermedio-9', 'intermedio', 'Que evalua la relacion riesgo beneficio?', 'a', 'Compara cuanto puedes perder frente a cuanto aspiras a ganar, para decidir si la operacion compensa antes de abrirla.', 9),
  ('intermedio-10', 'intermedio', 'Cuando conviene evaluar la relacion riesgo beneficio?', 'b', 'La relacion riesgo beneficio sirve para decidir antes de entrar, no para justificar una posicion cuando ya esta abierta.', 10),
  ('intermedio-11', 'intermedio', 'Que lectura puede reforzar un precio por encima de la media de 50 sesiones que sigue subiendo?', 'a', 'Si el precio se mantiene sobre una media relevante y esta ademas asciende, suele reforzar una lectura alcista del contexto.', 11),
  ('intermedio-12', 'intermedio', 'Cual es uno de los riesgos de usar un indicador de forma aislada?', 'c', 'Un indicador sin contexto puede llevar a conclusiones pobres o precipitadas. El precio, la tendencia y el riesgo tambien importan.', 12),
  ('intermedio-13', 'intermedio', 'Cual es el primer paso para calcular la varianza de una serie de rendimientos?', 'b', 'Para calcular la varianza primero necesitas la media. Luego comparas cada rendimiento con esa media.', 13),
  ('intermedio-14', 'intermedio', 'Por que se elevan al cuadrado las diferencias al calcular varianza?', 'a', 'Elevar al cuadrado evita que diferencias negativas y positivas se cancelen, y ademas da mas peso a desviaciones grandes.', 14),
  ('intermedio-15', 'intermedio', 'Que relacion hay entre varianza y desviacion estandar?', 'c', 'La desviacion estandar es la raiz cuadrada de la varianza. Por eso se expresa en unidades mas faciles de interpretar.', 15),
  ('intermedio-16', 'intermedio', 'Si una inversion gana un 4% y la inflacion es del 6%, que ocurre aproximadamente con la rentabilidad real?', 'b', 'Aunque la rentabilidad nominal sea positiva, la inflacion supera esa ganancia. El poder adquisitivo cae en terminos aproximados.', 16),
  ('intermedio-17', 'intermedio', 'Que mide la rentabilidad real?', 'a', 'La rentabilidad real ajusta la ganancia nominal por la inflacion, aproximando cuanto mejora o empeora el poder adquisitivo.', 17),
  ('intermedio-18', 'intermedio', 'Que compara el PER?', 'c', 'El PER relaciona el precio de una accion con el beneficio por accion. Es una referencia inicial de valoracion, no una conclusion final.', 18),
  ('intermedio-19', 'intermedio', 'Por que un PER bajo puede ser enganoso?', 'b', 'Un PER bajo puede indicar oportunidad, pero tambien que el mercado espera caidas de beneficios o problemas importantes.', 19),
  ('intermedio-20', 'intermedio', 'Que es el slippage en una operacion?', 'a', 'El slippage es la diferencia entre el precio que esperabas y el precio real de ejecucion. Suele empeorar con poca liquidez o mucha tension.', 20),
  ('avanzado-1', 'avanzado', 'Por que importa el drawdown aunque una estrategia termine ganando dinero?', 'a', 'Una estrategia puede ser rentable al final, pero si sus caidas son demasiado duras puede volverse psicologicamente y financieramente inviable.', 1),
  ('avanzado-2', 'avanzado', 'Si colocas un stop mas alejado, que deberia pasar con el tamano de posicion?', 'b', 'Cuanto mayor sea la distancia al stop, menor deberia ser el numero de acciones para no disparar el riesgo total.', 2),
  ('avanzado-3', 'avanzado', 'Que practica ayuda a reducir el sesgo de confirmacion?', 'c', 'Buscar evidencia en contra de tu propia idea te obliga a contrastarla y evita usar informacion solo para reafirmarte.', 3),
  ('avanzado-4', 'avanzado', 'Que riesgo tiene dar el mismo tamano a todas las operaciones?', 'a', 'No todas las ideas tienen el mismo riesgo. Igualar tamano sin contexto puede hacer que una operacion demasiado arriesgada pese mas de la cuenta.', 4),
  ('avanzado-5', 'avanzado', 'Que efecto suele tener un drawdown grande en el inversor?', 'b', 'El drawdown no afecta solo al capital; tambien afecta a la disciplina y a la capacidad de seguir el plan sin abandonarlo.', 5),
  ('avanzado-6', 'avanzado', 'Por que cambiar de opinion no siempre significa fallar?', 'c', 'En inversion actualizar una idea con datos nuevos es una fortaleza. Lo peligroso es aferrarse a una tesis rota por orgullo.', 6),
  ('avanzado-7', 'avanzado', 'Que intenta responder un backtesting?', 'a', 'El backtesting intenta ver como se habria comportado una estrategia en el pasado para obtener evidencia historica sobre su coherencia.', 7),
  ('avanzado-8', 'avanzado', 'Que riesgo tiene sobreajustar una estrategia al pasado?', 'c', 'Una estrategia demasiado adaptada al historico puede funcionar muy bien en los datos usados y muy mal fuera de muestra.', 8),
  ('avanzado-9', 'avanzado', 'Que aporta estudiar la correlacion entre activos?', 'b', 'La correlacion ayuda a saber si activos distintos realmente diversifican o si tenderan a moverse en la misma direccion.', 9),
  ('avanzado-10', 'avanzado', 'Que problema hay en una cartera con activos muy correlacionados?', 'a', 'Si varios activos se mueven casi igual, la diversificacion real es menor de lo que parece y la cartera puede sufrir al mismo tiempo.', 10),
  ('avanzado-11', 'avanzado', 'Que combina la esperanza matematica de una estrategia?', 'c', 'La esperanza matematica mezcla frecuencia de acierto con magnitud de ganancias y perdidas para estimar si el sistema tiene expectativa positiva.', 11),
  ('avanzado-12', 'avanzado', 'Puede una estrategia ser rentable aunque no acierte la mayoria de veces?', 'b', 'Si las operaciones ganadoras compensan suficientemente a las perdedoras, una estrategia puede funcionar aunque no acierte mas del 50%.', 12),
  ('avanzado-13', 'avanzado', 'Que sugiere una beta superior a 1?', 'a', 'Una beta superior a 1 suele indicar que el activo se mueve con mas intensidad que el mercado de referencia, aunque es una medida historica.', 13),
  ('avanzado-14', 'avanzado', 'Que mide el ratio Sharpe?', 'c', 'El Sharpe compara el exceso de rentabilidad con la volatilidad asumida, ayudando a evaluar rentabilidad ajustada al riesgo.', 14),
  ('avanzado-15', 'avanzado', 'Dos estrategias ganan un 12%, pero una tiene mucha menos volatilidad. Que puede decir el Sharpe?', 'b', 'Si la rentabilidad es similar pero una estrategia asume menos volatilidad, su rentabilidad ajustada al riesgo puede ser mejor.', 15),
  ('avanzado-16', 'avanzado', 'Cual es el peligro principal del apalancamiento?', 'a', 'El apalancamiento amplifica la exposicion. Por eso puede aumentar ganancias, pero tambien acelerar perdidas y llamadas de margen.', 16),
  ('avanzado-17', 'avanzado', 'Que puede ocurrir con una cartera apalancada si el mercado se mueve en contra?', 'c', 'Si las perdidas consumen demasiado margen, el broker puede exigir mas garantias o cerrar posiciones. Por eso el control de riesgo es critico.', 17),
  ('avanzado-18', 'avanzado', 'Que es un regimen de mercado?', 'b', 'Un regimen describe el entorno dominante: tendencia, lateralidad, alta volatilidad, baja volatilidad o crisis. Afecta a que estrategias funcionan mejor.', 18),
  ('avanzado-19', 'avanzado', 'Por que una estrategia puede fallar al cambiar el regimen de mercado?', 'a', 'Muchas estrategias dependen del entorno. Una tecnica que funciona en tendencia puede sufrir en lateralidad o alta volatilidad.', 19),
  ('avanzado-20', 'avanzado', 'Que limitacion importante tiene la beta?', 'c', 'La beta se calcula con datos historicos. Si cambia la empresa, el sector o el mercado, esa sensibilidad puede cambiar.', 20);

insert into public.concept_quiz_options (question_id, id, label, order_index) values
  ('base-1', 'a', 'Solo si ha subido mucho recientemente', 1),
  ('base-1', 'b', 'El riesgo y la posible perdida asociada', 2),
  ('base-1', 'c', 'Si todo el mundo habla de ella', 3),
  ('base-2', 'a', 'Comprar muchas empresas del mismo sector', 1),
  ('base-2', 'b', 'Comprar cualquier activo sin criterio', 2),
  ('base-2', 'c', 'Repartir el riesgo entre activos o sectores distintos', 3),
  ('base-3', 'a', 'Posible tendencia alcista', 1),
  ('base-3', 'b', 'Mercado sin direccion', 2),
  ('base-3', 'c', 'Senal segura de venta', 3),
  ('base-4', 'a', 'Que es imposible ganar dinero', 1),
  ('base-4', 'b', 'Que una sola decision puede afectar demasiado al resultado', 2),
  ('base-4', 'c', 'Que el broker te cobra mas comisiones', 3),
  ('base-5', 'a', 'Sube con fuerza y continuidad', 1),
  ('base-5', 'b', 'Cae con maximos crecientes', 2),
  ('base-5', 'c', 'No muestra una direccion clara', 3),
  ('base-6', 'a', 'Porque una gran perdida exige una ganancia aun mayor para volver al inicio', 1),
  ('base-6', 'b', 'Porque ya no se puede vender el activo', 2),
  ('base-6', 'c', 'Porque el mercado deja de moverse', 3),
  ('base-7', 'a', 'El numero de acciones que compras', 1),
  ('base-7', 'b', 'El tiempo durante el que planeas mantener la idea', 2),
  ('base-7', 'c', 'La comision que cobra el broker', 3),
  ('base-8', 'a', 'Cuanto puede variar el precio', 1),
  ('base-8', 'b', 'Cuanto dividendo reparte la empresa', 2),
  ('base-8', 'c', 'Cuantos anos lleva cotizando', 3),
  ('base-9', 'a', 'Garantiza que subira mas rapido', 1),
  ('base-9', 'b', 'Reduce automaticamente el riesgo de mercado', 2),
  ('base-9', 'c', 'Permite comprar o vender con mas facilidad', 3),
  ('base-10', 'a', 'Elegir siempre activos demasiado liquidos', 1),
  ('base-10', 'b', 'Ignorar la posible perdida y el riesgo asumido', 2),
  ('base-10', 'c', 'Analizar demasiado el contexto', 3),
  ('base-11', 'a', 'No entrar o hacerlo con mucha cautela', 1),
  ('base-11', 'b', 'Comprar mas porque puede sorprender', 2),
  ('base-11', 'c', 'Esperar a que otros lo compren antes', 3),
  ('base-12', 'a', 'No tienen ninguna relacion', 1),
  ('base-12', 'b', 'Son lo mismo con distinto nombre', 2),
  ('base-12', 'c', 'Una reparte riesgo y la otra lo concentra en menos decisiones', 3),
  ('base-13', 'a', 'Que las ganancias reinvertidas tambien pueden generar nuevas ganancias', 1),
  ('base-13', 'b', 'Que todas las inversiones ganan lo mismo cada ano', 2),
  ('base-13', 'c', 'Que las comisiones desaparecen con el tiempo', 3),
  ('base-14', 'a', 'Siempre sobre 1.000 euros', 1),
  ('base-14', 'b', 'Sobre 1.100 euros', 2),
  ('base-14', 'c', 'Sobre la comision del broker', 3),
  ('base-15', 'a', 'Una accion siempre tiene menos riesgo que un ETF', 1),
  ('base-15', 'b', 'Un ETF solo puede contener una empresa', 2),
  ('base-15', 'c', 'La accion depende de una empresa y el ETF puede agrupar muchas', 3),
  ('base-16', 'a', 'El comportamiento agregado de un grupo de activos', 1),
  ('base-16', 'b', 'La deuda exacta de una empresa', 2),
  ('base-16', 'c', 'Una orden obligatoria de compra', 3),
  ('base-17', 'a', 'Si, porque elimina cualquier riesgo', 1),
  ('base-17', 'b', 'No, hay que mirar si es sostenible y si el riesgo compensa', 2),
  ('base-17', 'c', 'Si, porque garantiza que el precio subira', 3),
  ('base-18', 'a', 'No hay ninguna diferencia', 1),
  ('base-18', 'b', 'El valor cambia cada segundo y el precio nunca cambia', 2),
  ('base-18', 'c', 'El precio es de mercado y el valor es una estimacion fundamentada', 3),
  ('base-19', 'a', 'Porque puede haber empeorado su valor real', 1),
  ('base-19', 'b', 'Porque las acciones caidas nunca rebotan', 2),
  ('base-19', 'c', 'Porque solo importa el volumen', 3),
  ('base-20', 'a', 'Garantia total de no perder', 1),
  ('base-20', 'b', 'Mas oportunidad para que actue la rentabilidad compuesta', 2),
  ('base-20', 'c', 'La desaparicion de la volatilidad diaria', 3),
  ('intermedio-1', 'a', 'Porque cambian cada hora de forma aleatoria', 1),
  ('intermedio-1', 'b', 'Porque el mercado rara vez respeta un precio exacto', 2),
  ('intermedio-1', 'c', 'Porque solo sirven en criptomonedas', 3),
  ('intermedio-2', 'a', 'Puede generar mas ruido y senales falsas', 1),
  ('intermedio-2', 'b', 'No permite ver nunca la tendencia', 2),
  ('intermedio-2', 'c', 'Solo funciona en marcos mensuales', 3),
  ('intermedio-3', 'a', 'Que hay que vender inmediatamente', 1),
  ('intermedio-3', 'b', 'Que el activo va a caer seguro', 2),
  ('intermedio-3', 'c', 'Que debe interpretarse junto con el contexto', 3),
  ('intermedio-4', 'a', 'Siempre deja de tener importancia', 1),
  ('intermedio-4', 'b', 'Puede convertirse en resistencia', 2),
  ('intermedio-4', 'c', 'Se convierte automaticamente en una senal de compra', 3),
  ('intermedio-5', 'a', 'Acertar siempre el mejor punto de entrada', 1),
  ('intermedio-5', 'b', 'Dar mas senales por semana', 2),
  ('intermedio-5', 'c', 'Filtrar mejor el ruido del precio', 3),
  ('intermedio-6', 'a', 'Combinar la zona con volumen, tendencia y riesgo', 1),
  ('intermedio-6', 'b', 'Mirarla sin usar ningun otro dato', 2),
  ('intermedio-6', 'c', 'Cambiar de zona cada vez que cierra una vela', 3),
  ('intermedio-7', 'a', 'Que la ruptura es irrelevante', 1),
  ('intermedio-7', 'b', 'Que el movimiento puede tener mas credibilidad', 2),
  ('intermedio-7', 'c', 'Que el precio se movera menos despues', 3),
  ('intermedio-8', 'a', 'Una ruptura con mucho volumen', 1),
  ('intermedio-8', 'b', 'Una ruptura que se mantiene varios dias', 2),
  ('intermedio-8', 'c', 'Una superacion temporal que pierde fuerza y vuelve al rango', 3),
  ('intermedio-9', 'a', 'La proporcion entre posible perdida y posible ganancia', 1),
  ('intermedio-9', 'b', 'La relacion entre volumen y liquidez', 2),
  ('intermedio-9', 'c', 'La diferencia entre dos medias moviles', 3),
  ('intermedio-10', 'a', 'Solo al cerrar la operacion', 1),
  ('intermedio-10', 'b', 'Antes de abrir la operacion', 2),
  ('intermedio-10', 'c', 'Solo si el activo tiene mucho volumen', 3),
  ('intermedio-11', 'a', 'Una posible continuidad alcista', 1),
  ('intermedio-11', 'b', 'Una senal segura de agotamiento', 2),
  ('intermedio-11', 'c', 'Que el activo esta sin tendencia', 3),
  ('intermedio-12', 'a', 'Que siempre acierta demasiado', 1),
  ('intermedio-12', 'b', 'Que elimina la necesidad de gestionar riesgo', 2),
  ('intermedio-12', 'c', 'Que puedes sacar una conclusion incompleta o enganosa', 3),
  ('intermedio-13', 'a', 'Elegir el rendimiento mas alto', 1),
  ('intermedio-13', 'b', 'Calcular la media de los rendimientos', 2),
  ('intermedio-13', 'c', 'Multiplicar todos los precios entre si', 3),
  ('intermedio-14', 'a', 'Para que no se cancelen y para penalizar movimientos grandes', 1),
  ('intermedio-14', 'b', 'Para convertir siempre una perdida en ganancia', 2),
  ('intermedio-14', 'c', 'Para eliminar la volatilidad del activo', 3),
  ('intermedio-15', 'a', 'Son conceptos sin relacion', 1),
  ('intermedio-15', 'b', 'La varianza es la raiz cuadrada de la desviacion', 2),
  ('intermedio-15', 'c', 'La desviacion estandar es la raiz cuadrada de la varianza', 3),
  ('intermedio-16', 'a', 'Es claramente positiva', 1),
  ('intermedio-16', 'b', 'Es negativa en terminos aproximados', 2),
  ('intermedio-16', 'c', 'No cambia porque la inflacion no importa', 3),
  ('intermedio-17', 'a', 'La rentabilidad despues de considerar la inflacion', 1),
  ('intermedio-17', 'b', 'Solo el dividendo cobrado', 2),
  ('intermedio-17', 'c', 'La rentabilidad antes de cualquier ajuste', 3),
  ('intermedio-18', 'a', 'Volumen y liquidez', 1),
  ('intermedio-18', 'b', 'Precio actual y soporte tecnico', 2),
  ('intermedio-18', 'c', 'Precio de la accion y beneficio por accion', 3),
  ('intermedio-19', 'a', 'Porque siempre significa que la empresa crecera mas', 1),
  ('intermedio-19', 'b', 'Porque puede reflejar deterioro o expectativas negativas', 2),
  ('intermedio-19', 'c', 'Porque solo existe en criptomonedas', 3),
  ('intermedio-20', 'a', 'La diferencia entre precio esperado y precio ejecutado', 1),
  ('intermedio-20', 'b', 'El dividendo anual de una accion', 2),
  ('intermedio-20', 'c', 'La media movil de largo plazo', 3),
  ('avanzado-1', 'a', 'Porque una caida excesiva puede ser dificil de soportar y recuperar', 1),
  ('avanzado-1', 'b', 'Porque elimina automaticamente la rentabilidad futura', 2),
  ('avanzado-1', 'c', 'Porque solo afecta a carteras institucionales', 3),
  ('avanzado-2', 'a', 'Aumentar para aprovechar mas el movimiento', 1),
  ('avanzado-2', 'b', 'Reducirse para mantener el riesgo controlado', 2),
  ('avanzado-2', 'c', 'Quedarse siempre igual', 3),
  ('avanzado-3', 'a', 'Buscar solo opiniones que confirmen tu idea', 1),
  ('avanzado-3', 'b', 'Mantener una operacion aunque aparezcan senales contrarias', 2),
  ('avanzado-3', 'c', 'Preguntarte que evidencias demostrarian que estabas equivocado', 3),
  ('avanzado-4', 'a', 'Que ignores diferencias de volatilidad, stop o calidad de la idea', 1),
  ('avanzado-4', 'b', 'Que el beneficio siempre sea menor', 2),
  ('avanzado-4', 'c', 'Que no puedas diversificar nunca', 3),
  ('avanzado-5', 'a', 'Ninguno, si la estrategia era buena', 1),
  ('avanzado-5', 'b', 'Puede erosionar la confianza y hacer abandonar el sistema', 2),
  ('avanzado-5', 'c', 'Solo afecta cuando se opera con derivados', 3),
  ('avanzado-6', 'a', 'Porque el mercado siempre da una segunda oportunidad inmediata', 1),
  ('avanzado-6', 'b', 'Porque vender una mala posicion garantiza beneficio', 2),
  ('avanzado-6', 'c', 'Porque revisar la tesis con nueva informacion forma parte de decidir bien', 3),
  ('avanzado-7', 'a', 'Como se habria comportado una estrategia con datos historicos', 1),
  ('avanzado-7', 'b', 'Que precio tendra un activo manana', 2),
  ('avanzado-7', 'c', 'Que empresa va a publicar mejores resultados', 3),
  ('avanzado-8', 'a', 'Que se vuelva demasiado simple', 1),
  ('avanzado-8', 'b', 'Que deje de tener costes', 2),
  ('avanzado-8', 'c', 'Que parezca robusta en el pasado pero falle en el futuro', 3),
  ('avanzado-9', 'a', 'Asegurar que todos subiran a la vez', 1),
  ('avanzado-9', 'b', 'Entender si se mueven de forma parecida o diferente', 2),
  ('avanzado-9', 'c', 'Reducir automaticamente el drawdown', 3),
  ('avanzado-10', 'a', 'Que la diversificacion puede ser mas aparente que real', 1),
  ('avanzado-10', 'b', 'Que siempre ganara menos', 2),
  ('avanzado-10', 'c', 'Que no podras vender ninguno', 3),
  ('avanzado-11', 'a', 'Solo el porcentaje de operaciones ganadoras', 1),
  ('avanzado-11', 'b', 'Solo el ratio beneficio riesgo', 2),
  ('avanzado-11', 'c', 'La probabilidad de ganar y perder con el tamano medio de cada resultado', 3),
  ('avanzado-12', 'a', 'No, siempre necesita acertar mas de la mitad', 1),
  ('avanzado-12', 'b', 'Si, si gana bastante mas cuando acierta que lo que pierde cuando falla', 2),
  ('avanzado-12', 'c', 'Solo si usa apalancamiento', 3),
  ('avanzado-13', 'a', 'Que tiende a moverse mas que el mercado', 1),
  ('avanzado-13', 'b', 'Que no tiene riesgo', 2),
  ('avanzado-13', 'c', 'Que siempre paga mas dividendos', 3),
  ('avanzado-14', 'a', 'Solo el numero de operaciones realizadas', 1),
  ('avanzado-14', 'b', 'La comision media del broker', 2),
  ('avanzado-14', 'c', 'Rentabilidad extra por unidad de volatilidad', 3),
  ('avanzado-15', 'a', 'Que ambas son identicas en riesgo', 1),
  ('avanzado-15', 'b', 'Que la menos volatil puede tener mejor rentabilidad ajustada al riesgo', 2),
  ('avanzado-15', 'c', 'Que la mas volatil siempre es superior', 3),
  ('avanzado-16', 'a', 'Amplifica las perdidas igual que las ganancias', 1),
  ('avanzado-16', 'b', 'Elimina la necesidad de stops', 2),
  ('avanzado-16', 'c', 'Reduce automaticamente la volatilidad', 3),
  ('avanzado-17', 'a', 'Que las perdidas se congelen', 1),
  ('avanzado-17', 'b', 'Que el riesgo desaparezca', 2),
  ('avanzado-17', 'c', 'Que aparezcan llamadas de margen o cierres forzados', 3),
  ('avanzado-18', 'a', 'Una lista fija de empresas rentables', 1),
  ('avanzado-18', 'b', 'El entorno dominante en el que se mueve el mercado', 2),
  ('avanzado-18', 'c', 'Una orden para comprar siempre al cierre', 3),
  ('avanzado-19', 'a', 'Porque las condiciones que la favorecian pueden desaparecer', 1),
  ('avanzado-19', 'b', 'Porque los precios dejan de existir', 2),
  ('avanzado-19', 'c', 'Porque los indicadores se vuelven ilegales', 3),
  ('avanzado-20', 'a', 'Que solo sirve para medir dividendos', 1),
  ('avanzado-20', 'b', 'Que nunca cambia con el tiempo', 2),
  ('avanzado-20', 'c', 'Que es historica y puede dejar de representar el riesgo futuro', 3);
